# Generated by Django 4.0.4 on 2022-06-19 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petlovers', '0003_alter_product_description_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dateAdded',
            field=models.DateField(null=True),
        ),
    ]
