# Generated by Django 4.0.4 on 2022-06-26 22:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petlovers', '0005_rename_productname_product_product_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='dateAdded',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
