# Generated by Django 4.0.4 on 2022-07-13 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petlovers', '0007_product_image_product_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='type_user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_name',
        ),
        migrations.AddField(
            model_name='user',
            name='adress',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='rut',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
