# Generated by Django 4.0.4 on 2022-07-13 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petlovers', '0009_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
