# Generated by Django 4.0.4 on 2022-07-13 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petlovers', '0010_remove_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
